/**
 * Gmail-safe early access invite email builder.
 *
 * Produces table-based HTML + plain-text sibling for cold email sends. The
 * four showpiece compositions are pulled in as hosted PNGs generated by
 * `scripts/generate-email-compositions.mjs`. Everything else is real text in
 * <table> / <td> with inline styles, so the email survives Gmail's HTML
 * sanitizer without layout breakage.
 *
 * Hard rules enforced at build time (see `assertEmailSafe`):
 *  - No <script>, <form>, <svg>, <style> (outside MSO conditionals), class=
 *  - No CSS properties Gmail strips (position, transform, mask-image, etc.)
 *  - Total HTML weight must stay under Gmail's ~102 KB clip threshold.
 *
 * This is intentionally a parallel, separate builder from
 * `leadEarlyAccessEmailHtml.ts`. The rich one stays as the admin preview and
 * web view; this one is what actually gets copy-pasted into Instantly.
 */

import type { LeadEarlyAccessData } from "@/data/leads/_schema";
import {
  EARLY_ACCESS_EMAIL_COPY,
  EARLY_ACCESS_TRIAL_USAGE_MINUTES_LIMIT,
  buildEarlyAccessChips,
  buildEarlyAccessPreheader,
  buildEarlyAccessSalutationPlainText,
  earlyAccessGreetingFirstName,
} from "@/data/leadEarlyAccessCopy";
import { EARLY_ACCESS_TERMS } from "@/data/leads/_schema";
import {
  BIZMIS_BORDER_HEX,
  BIZMIS_MUTED_FG_HEX,
  BIZMIS_PRIMARY_HEX,
  BIZMIS_WARM_BG_HEX,
} from "@/lib/bizmisBrandColors";

export const SAFE_EMAIL_DEFAULT_BASE_URL = "https://www.bizmis.ai" as const;
export const SAFE_EMAIL_MAX_BYTES = 102_000;
export const SAFE_EMAIL_WARN_BYTES = 60_000;

const CARD_MAX_WIDTH_PX = 600;
const HERO_BANNER_DISPLAY_WIDTH_PX = 600;
const HERO_BANNER_DISPLAY_HEIGHT_PX = 192;
const DESKTOP_MOCKUP_DISPLAY_WIDTH_PX = 560;
const DESKTOP_MOCKUP_DISPLAY_HEIGHT_PX = 373;
const PHONE_MOCKUP_DISPLAY_WIDTH_PX = 280;
const PHONE_MOCKUP_DISPLAY_HEIGHT_PX = 373;
const PLUG_AND_PLAY_DISPLAY_WIDTH_PX = 560;
const PLUG_AND_PLAY_DISPLAY_HEIGHT_PX = 400;

const FOREGROUND_HEX = "#32281B";
const MUTED_LIGHT_HEX = "#B5A48E";
const MUTED_SUBTLE_HEX = "#C8BBA4";
const SOFT_CALLOUT_BG_HEX = "#FDF5EC";
const CTA_BG_HEX = "#32281B";

const SYSTEM_FONT_STACK =
  "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,Helvetica,sans-serif";

const LINK_SUCCESS_GREEN_HEX = "#108849";

export type BuildSafeEmailOptions = {
  /**
   * Base URL used for absolute image src values. Leave empty ("") to emit
   * relative URLs (admin iframe preview against the dev server). Pass the
   * production origin (default "https://www.bizmis.ai") for outbound copy.
   */
  baseUrl?: string;
};

export type SafeEmailBuildResult = {
  html: string;
  plainText: string;
  htmlSizeBytes: number;
  warnings: string[];
};

// Public API.

export function buildLeadEarlyAccessEmailHtmlSafe(
  lead: LeadEarlyAccessData,
  options: BuildSafeEmailOptions = {},
): SafeEmailBuildResult {
  const baseUrl = normalizeBaseUrl(options.baseUrl);
  const html = renderSafeHtml(lead, baseUrl);
  const htmlSizeBytes = new TextEncoder().encode(html).byteLength;
  const warnings = assertEmailSafe(html, htmlSizeBytes);
  const plainText = renderPlainText(lead);
  return { html, plainText, htmlSizeBytes, warnings };
}

export async function copyLeadEarlyAccessSafeHtmlSource(
  lead: LeadEarlyAccessData,
): Promise<void> {
  const { html } = buildLeadEarlyAccessEmailHtmlSafe(lead, {
    baseUrl: SAFE_EMAIL_DEFAULT_BASE_URL,
  });
  await navigator.clipboard.writeText(html);
}

// Base URL handling.

function normalizeBaseUrl(raw: string | undefined): string {
  if (raw === undefined) return SAFE_EMAIL_DEFAULT_BASE_URL;
  if (raw === "") return "";
  return raw.replace(/\/$/, "");
}

function absUrl(baseUrl: string, publicPath: string): string {
  const safePath = publicPath.startsWith("/") ? publicPath : `/${publicPath}`;
  return `${baseUrl}${safePath}`;
}

// HTML rendering.

function renderSafeHtml(lead: LeadEarlyAccessData, baseUrl: string): string {
  const { storeCap, shopifyAppUrl } = EARLY_ACCESS_TERMS;
  const copy = EARLY_ACCESS_EMAIL_COPY;

  const storeName = escapeHtml(lead.storeName);
  const accent = ensureHex(lead.primaryColor);
  const storeAccent = resolveStoreAccentForEmail(accent);
  const leadHandle = encodeURIComponent(lead.id);
  const earlyAccessCode = lead.couponCode;

  const heroBannerUrl = absUrl(baseUrl, `/invite-cards/leads/${lead.id}/email/hero-banner.png`);
  const desktopMockupUrl = absUrl(baseUrl, `/invite-cards/leads/${lead.id}/email/desktop-mockup.png`);
  const phoneMockupUrl = absUrl(baseUrl, `/invite-cards/leads/${lead.id}/email/phone-mockup.png`);
  const plugAndPlayUrl = absUrl(baseUrl, `/invite-cards/leads/${lead.id}/email/plug-and-play.png`);

  const installUrlBase = `${shopifyAppUrl}?ref=${leadHandle}`;
  const installUrlWithCode = `${installUrlBase}&code=${encodeURIComponent(earlyAccessCode)}`;

  const salutationText = escapeHtml(buildEarlyAccessSalutationPlainText(lead.storeName, lead.leadContactName));

  const pitchHtml = buildPitchParagraphHtml(storeName, storeAccent);
  const softCtaHtml = buildSoftCtaCalloutHtml(installUrlBase, storeCap);
  const ctaBoxHtml = buildCtaBoxHtml(installUrlWithCode, earlyAccessCode, copy.ctaLabel);

  const preheader = escapeHtml(buildEarlyAccessPreheader(lead.storeName, storeCap));

  const heroImageHtml = buildLinkedHeroImage({
    href: installUrlBase,
    src: heroBannerUrl,
    alt: `Bizmis Early Access Invite for ${lead.storeName}`,
    widthPx: HERO_BANNER_DISPLAY_WIDTH_PX,
    heightPx: HERO_BANNER_DISPLAY_HEIGHT_PX,
  });
  const desktopImageHtml = buildCenteredImage({
    src: desktopMockupUrl,
    alt: `Bizmis voice clerk on the ${lead.storeName} storefront recommending ${escapeHtml(lead.salesProducts[lead.salesRecommendedIndex].title)}`,
    widthPx: DESKTOP_MOCKUP_DISPLAY_WIDTH_PX,
    heightPx: DESKTOP_MOCKUP_DISPLAY_HEIGHT_PX,
    borderRadiusPx: 12,
    fullWidth: true,
  });
  const phoneImageHtml = buildCenteredImage({
    src: phoneMockupUrl,
    alt: `Bizmis answering a ${lead.storeName} customer support question`,
    widthPx: PHONE_MOCKUP_DISPLAY_WIDTH_PX,
    heightPx: PHONE_MOCKUP_DISPLAY_HEIGHT_PX,
    borderRadiusPx: 12,
    fullWidth: false,
  });
  const plugAndPlayImageHtml = buildCenteredImage({
    src: plugAndPlayUrl,
    alt: `One-click Shopify install — Bizmis syncs with your products, discounts, customers, and orders`,
    widthPx: PLUG_AND_PLAY_DISPLAY_WIDTH_PX,
    heightPx: PLUG_AND_PLAY_DISPLAY_HEIGHT_PX,
    borderRadiusPx: 12,
    fullWidth: true,
  });

  const supportingCopyConvert = "Convert more visitors. Increase order value. Build customer loyalty.";
  const supportingCopySupport = "Save support hours. Earn better reviews. Grow repeat sales.";

  return `<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>${escapeHtml(copy.emailDocumentTitle)}</title>
<!--[if mso]>
<style>table,td{font-family:Arial,sans-serif !important;} a{text-decoration:none;}</style>
<![endif]-->
</head>
<body style="margin:0;padding:0;background-color:${BIZMIS_WARM_BG_HEX};-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">

<div style="display:none;font-size:1px;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">
${preheader}
</div>

<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:${BIZMIS_WARM_BG_HEX};">
<tr>
<td align="center" style="padding:28px 16px;">

<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="${CARD_MAX_WIDTH_PX}" style="max-width:${CARD_MAX_WIDTH_PX}px;width:100%;background-color:#ffffff;border:1px solid ${BIZMIS_BORDER_HEX};border-radius:16px;overflow:hidden;">

<tr>
<td style="padding:0;line-height:0;font-size:0;background-color:${accent};">
${heroImageHtml}
</td>
</tr>

<tr>
<td style="padding:32px 32px 0 32px;">
<p style="margin:0;font-family:${SYSTEM_FONT_STACK};font-size:11px;line-height:1.6;color:${BIZMIS_MUTED_FG_HEX};letter-spacing:0.01em;">
${salutationText}
</p>
</td>
</tr>

<tr>
<td style="padding:20px 32px 0 32px;">
${pitchHtml}
</td>
</tr>

<tr>
<td style="padding:22px 32px 0 32px;">
${softCtaHtml}
</td>
</tr>

<tr>
<td style="padding:28px 20px 0 20px;line-height:0;font-size:0;" align="center">
${desktopImageHtml}
</td>
</tr>

<tr>
<td style="padding:22px 32px 0 32px;">
<p style="margin:0;font-family:${SYSTEM_FONT_STACK};font-size:13px;line-height:1.7;color:${FOREGROUND_HEX};text-align:center;font-weight:500;">
${escapeHtml(supportingCopyConvert)}
</p>
</td>
</tr>

<tr>
<td style="padding:28px 20px 0 20px;line-height:0;font-size:0;" align="center">
${phoneImageHtml}
</td>
</tr>

<tr>
<td style="padding:22px 32px 0 32px;">
<p style="margin:0;font-family:${SYSTEM_FONT_STACK};font-size:13px;line-height:1.7;color:${FOREGROUND_HEX};text-align:center;font-weight:500;">
${escapeHtml(supportingCopySupport)}
</p>
</td>
</tr>

<tr>
<td style="padding:28px 20px 0 20px;line-height:0;font-size:0;" align="center">
${plugAndPlayImageHtml}
</td>
</tr>

<tr>
<td style="padding:28px 32px 0 32px;" align="center">
${ctaBoxHtml}
</td>
</tr>

<tr>
<td style="padding:28px 40px 32px 40px;text-align:center;border-top:1px solid #EBE6DF;">
<p style="margin:0 0 10px 0;font-family:${SYSTEM_FONT_STACK};font-size:10px;line-height:1.65;color:${MUTED_LIGHT_HEX};">
${escapeHtml(copy.proofLine)}
</p>
<p style="margin:0 0 10px 0;font-family:${SYSTEM_FONT_STACK};font-size:10px;line-height:1.55;color:${MUTED_LIGHT_HEX};">
Questions? Just reply to this email (<a href="mailto:${escapeHtml(copy.contactEmail)}" style="color:${BIZMIS_MUTED_FG_HEX};text-decoration:none;">${escapeHtml(copy.contactEmail)}</a>).
</p>
<a href="https://bizmis.ai" target="_blank" rel="noopener noreferrer" style="font-family:${SYSTEM_FONT_STACK};font-size:10px;font-weight:500;color:${BIZMIS_MUTED_FG_HEX};text-decoration:none;">bizmis.ai</a>
</td>
</tr>

</table>
</td>
</tr>
</table>

</body>
</html>`;
}

// HTML fragment helpers.

type LinkedImageSpec = {
  href: string;
  src: string;
  alt: string;
  widthPx: number;
  heightPx: number;
};

function buildLinkedHeroImage(spec: LinkedImageSpec): string {
  return `<a href="${escapeAttr(spec.href)}" target="_blank" rel="noopener noreferrer" style="display:block;">
<img src="${escapeAttr(spec.src)}" alt="${escapeAttr(spec.alt)}" width="${spec.widthPx}" height="${spec.heightPx}" style="display:block;width:100%;max-width:${spec.widthPx}px;height:auto;border:0;" />
</a>`;
}

type CenteredImageSpec = {
  src: string;
  alt: string;
  widthPx: number;
  heightPx: number;
  borderRadiusPx: number;
  fullWidth: boolean;
};

function buildCenteredImage(spec: CenteredImageSpec): string {
  const widthAttr = spec.fullWidth
    ? `width:100%;max-width:${spec.widthPx}px;height:auto;`
    : `max-width:${spec.widthPx}px;height:auto;margin:0 auto;`;
  return `<img src="${escapeAttr(spec.src)}" alt="${escapeAttr(spec.alt)}" width="${spec.widthPx}" height="${spec.heightPx}" style="display:block;${widthAttr}border:0;border-radius:${spec.borderRadiusPx}px;" />`;
}

function buildPitchParagraphHtml(storeName: string, storeAccent: string): string {
  const c = EARLY_ACCESS_EMAIL_COPY;
  const fgStyle = `font-family:${SYSTEM_FONT_STACK};font-size:15px;line-height:1.72;color:${FOREGROUND_HEX};`;
  return `<p style="margin:0;${fgStyle}">
${escapeHtml(c.inviteSentenceLeadNamedBeforeBizmis)}<span style="font-weight:600;color:${BIZMIS_PRIMARY_HEX};">${escapeHtml(c.inviteSentenceBizmisWord)}</span>${escapeHtml(c.inviteSentenceAfterFirstBizmis)}<span style="color:${storeAccent};font-weight:600;">${storeName}</span>${escapeHtml(c.inviteSentenceAfterStorePreValue)}<strong style="font-weight:600;">${escapeHtml(c.inviteSentenceValueDriveSales)}</strong>${escapeHtml(c.inviteSentenceValueJoiner)}<strong style="font-weight:600;">${escapeHtml(c.inviteSentenceValueEaseSupport)}</strong>${escapeHtml(c.inviteSentenceAfterStorePostValue)}
</p>`;
}

function buildSoftCtaCalloutHtml(installUrl: string, storeCap: number): string {
  const c = EARLY_ACCESS_EMAIL_COPY;
  const chips = buildEarlyAccessChips(storeCap);
  return `<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%">
<tr>
<td style="background-color:${SOFT_CALLOUT_BG_HEX};border-left:3px solid ${BIZMIS_PRIMARY_HEX};padding:14px 18px;border-radius:0 8px 8px 0;">
<p style="margin:0;font-family:${SYSTEM_FONT_STACK};font-size:14px;line-height:1.45;">
<a href="${escapeAttr(installUrl)}" target="_blank" rel="noopener noreferrer" style="color:${BIZMIS_PRIMARY_HEX};font-weight:600;text-decoration:none;">${escapeHtml(c.softCtaAboveMockupPrimaryLine)} &rarr;</a>
<span style="color:${MUTED_LIGHT_HEX};font-size:11px;font-style:italic;">&nbsp;&nbsp;${escapeHtml(c.softCtaAboveMockupInlineTagline)}</span>
</p>
<p style="margin:8px 0 0 0;font-family:${SYSTEM_FONT_STACK};font-size:10px;color:${MUTED_LIGHT_HEX};letter-spacing:0.02em;">
${chips.map((chip) => escapeHtml(chip)).join(" &middot; ")}
</p>
</td>
</tr>
</table>`;
}

function buildCtaBoxHtml(installUrlWithCode: string, earlyAccessCode: string, ctaLabel: string): string {
  const c = EARLY_ACCESS_EMAIL_COPY;
  const footnote = `* Up to ${EARLY_ACCESS_TRIAL_USAGE_MINUTES_LIMIT} minutes of included usage.`;
  return `<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="border:1px dashed ${BIZMIS_BORDER_HEX};border-radius:14px;">
<tr>
<td style="padding:24px 28px 14px 28px;" align="center">
<p style="margin:0;font-family:${SYSTEM_FONT_STACK};font-size:9px;color:${MUTED_LIGHT_HEX};letter-spacing:0.02em;">
${escapeHtml(c.couponLabel)}
<span style="color:${BIZMIS_MUTED_FG_HEX};font-size:10px;letter-spacing:0.04em;">&nbsp;${escapeHtml(earlyAccessCode)}</span>
</p>
</td>
</tr>
<tr>
<td style="padding:0 28px 24px 28px;" align="center">
<table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center">
<tr>
<td align="center" bgcolor="${CTA_BG_HEX}" style="border-radius:12px;">
<a href="${escapeAttr(installUrlWithCode)}" target="_blank" rel="noopener noreferrer" style="display:inline-block;padding:14px 32px;font-family:${SYSTEM_FONT_STACK};font-size:13px;font-weight:600;color:#ffffff;text-decoration:none;border-radius:12px;">
${escapeHtml(ctaLabel)}
</a>
</td>
</tr>
</table>
</td>
</tr>
</table>
<p style="margin:10px 0 0 0;font-family:${SYSTEM_FONT_STACK};font-size:8px;line-height:1.4;color:${MUTED_SUBTLE_HEX};text-align:center;">
${escapeHtml(footnote)}
</p>`;
}

// Plain text rendering.

function renderPlainText(lead: LeadEarlyAccessData): string {
  const { storeCap, shopifyAppUrl } = EARLY_ACCESS_TERMS;
  const c = EARLY_ACCESS_EMAIL_COPY;
  const leadHandle = encodeURIComponent(lead.id);
  const installUrl = `${shopifyAppUrl}?ref=${leadHandle}`;
  const installUrlWithCode = `${installUrl}&code=${encodeURIComponent(lead.couponCode)}`;
  const contactFirst = earlyAccessGreetingFirstName(lead.leadContactName);
  const salutation = contactFirst
    ? `${c.greetingDear} ${contactFirst},`
    : `${c.greetingDear} ${lead.storeName}${c.greetingStoreTeamSuffix}`;
  const pitch = [
    c.inviteSentenceLeadNamedBeforeBizmis,
    c.inviteSentenceBizmisWord,
    c.inviteSentenceAfterFirstBizmis,
    lead.storeName,
    c.inviteSentenceAfterStorePreValue,
    c.inviteSentenceValueDriveSales,
    c.inviteSentenceValueJoiner,
    c.inviteSentenceValueEaseSupport,
    c.inviteSentenceAfterStorePostValue,
  ].join("");
  const chips = buildEarlyAccessChips(storeCap).join(" · ");

  return [
    salutation,
    "",
    pitch,
    "",
    `${c.softCtaAboveMockupPrimaryLine}: ${installUrl}`,
    c.softCtaAboveMockupInlineTagline,
    chips,
    "",
    "Convert more visitors. Increase order value. Build customer loyalty.",
    "Save support hours. Earn better reviews. Grow repeat sales.",
    "One-click Shopify install. Bizmis syncs with your products, discounts, customers, and orders.",
    "",
    `${c.couponLabel} ${lead.couponCode}`,
    `${c.ctaLabel}: ${installUrlWithCode}`,
    `* Up to ${EARLY_ACCESS_TRIAL_USAGE_MINUTES_LIMIT} minutes of included usage.`,
    "",
    c.proofLine,
    `Questions? Just reply to this email (${c.contactEmail}).`,
    "",
    "bizmis.ai",
  ].join("\n");
}

// Safety linter.

type ForbiddenRule = { pattern: RegExp; label: string };

const FORBIDDEN_TAGS: ForbiddenRule[] = [
  { pattern: /<script[\s>]/i, label: "<script> tag" },
  { pattern: /<form[\s>]/i, label: "<form> tag" },
  { pattern: /<svg[\s>]/i, label: "<svg> tag" },
  { pattern: /<style[\s>]/i, label: "<style> tag (outside MSO conditional)" },
  { pattern: /\sclass\s*=\s*["']/i, label: "class= attribute" },
  { pattern: /\son[a-z]+\s*=\s*["']/i, label: "on* event handler attribute" },
];

const FORBIDDEN_CSS: ForbiddenRule[] = [
  { pattern: /position\s*:\s*(absolute|relative|fixed)/i, label: "CSS position" },
  { pattern: /transform\s*:/i, label: "CSS transform" },
  { pattern: /-webkit-mask-image\s*:/i, label: "CSS -webkit-mask-image" },
  { pattern: /[\s;]mask-image\s*:/i, label: "CSS mask-image" },
  { pattern: /mix-blend-mode\s*:/i, label: "CSS mix-blend-mode" },
  { pattern: /backdrop-filter\s*:/i, label: "CSS backdrop-filter" },
  { pattern: /clip-path\s*:/i, label: "CSS clip-path" },
  { pattern: /[\s;:]calc\s*\(/i, label: "CSS calc()" },
  { pattern: /var\s*\(\s*--/i, label: "CSS variable (var(--...))" },
  { pattern: /margin\s*:\s*-/i, label: "negative margin" },
];

function assertEmailSafe(html: string, htmlSizeBytes: number): string[] {
  const warnings: string[] = [];
  const errors: string[] = [];

  const withoutMsoConditionals = html.replace(
    /<!--\[if[\s\S]*?<!\[endif\]-->/gi,
    "",
  );

  for (const rule of FORBIDDEN_TAGS) {
    if (rule.pattern.test(withoutMsoConditionals)) {
      errors.push(`Forbidden: ${rule.label}`);
    }
  }
  for (const rule of FORBIDDEN_CSS) {
    if (rule.pattern.test(withoutMsoConditionals)) {
      errors.push(`Forbidden: ${rule.label}`);
    }
  }

  if (htmlSizeBytes > SAFE_EMAIL_MAX_BYTES) {
    errors.push(
      `HTML is ${(htmlSizeBytes / 1024).toFixed(1)} KB, over Gmail's ${(SAFE_EMAIL_MAX_BYTES / 1024).toFixed(0)} KB clip threshold`,
    );
  } else if (htmlSizeBytes > SAFE_EMAIL_WARN_BYTES) {
    warnings.push(
      `HTML is ${(htmlSizeBytes / 1024).toFixed(1)} KB, approaching Gmail's ${(SAFE_EMAIL_MAX_BYTES / 1024).toFixed(0)} KB clip threshold`,
    );
  }

  if (errors.length > 0) {
    throw new Error(
      `Gmail-safe email build failed:\n  - ${errors.join("\n  - ")}`,
    );
  }

  return warnings;
}

// Utilities.

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeAttr(s: string): string {
  return escapeHtml(s);
}

function ensureHex(value: string): string {
  const v = value?.trim() ?? "";
  if (/^#[0-9A-Fa-f]{6}$/.test(v)) return v;
  return BIZMIS_PRIMARY_HEX;
}

/**
 * The pitch paragraph highlights the store name in an accent. If the lead's
 * primaryColor is too light (white/very pale navbar leads), fall back to a
 * readable dark-green accent to avoid invisible text on the white card.
 */
function resolveStoreAccentForEmail(primaryHex: string): string {
  const lum = relativeLuminance(primaryHex);
  if (lum > 0.82) return LINK_SUCCESS_GREEN_HEX;
  return primaryHex;
}

function relativeLuminance(hex: string): number {
  const match = /^#([0-9A-Fa-f]{6})$/.exec(hex);
  if (!match) return 0;
  const r = parseInt(match[1].slice(0, 2), 16) / 255;
  const g = parseInt(match[1].slice(2, 4), 16) / 255;
  const b = parseInt(match[1].slice(4, 6), 16) / 255;
  const channel = (c: number) => (c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
}
