/** Generated by scripts/sync-lead-product-manifest.mjs — do not edit by hand. */

export type LeadProductSlot = "a" | "b" | "c";

export const LEAD_PRODUCT_URLS: Record<string, Partial<Record<LeadProductSlot, string>>> = {
  "bluetti": { a: "/invite-cards/leads/bluetti/product-a.webp", b: "/invite-cards/leads/bluetti/product-b.png", c: "/invite-cards/leads/bluetti/product-c.webp" },
  "bulova": { a: "/invite-cards/leads/bulova/product-a.png", b: "/invite-cards/leads/bulova/product-b.png", c: "/invite-cards/leads/bulova/product-c.png" },
  "burrow": { a: "/invite-cards/leads/burrow/product-a.png", b: "/invite-cards/leads/burrow/product-b.png", c: "/invite-cards/leads/burrow/product-c.png" },
  "crownandcaliber": { a: "/invite-cards/leads/crownandcaliber/product-a.png", b: "/invite-cards/leads/crownandcaliber/product-b.png", c: "/invite-cards/leads/crownandcaliber/product-c.png" },
  "emotiva": { a: "/invite-cards/leads/emotiva/product-a.png", b: "/invite-cards/leads/emotiva/product-b.png", c: "/invite-cards/leads/emotiva/product-c.png" },
  "floyd": { a: "/invite-cards/leads/floyd/product-a.png", b: "/invite-cards/leads/floyd/product-b.png", c: "/invite-cards/leads/floyd/product-c.png" },
  "glossier": { a: "/invite-cards/leads/glossier/product-a.jpg", b: "/invite-cards/leads/glossier/product-b.jpg", c: "/invite-cards/leads/glossier/product-c.jpg" },
  "glowforge": { a: "/invite-cards/leads/glowforge/product-a.webp", b: "/invite-cards/leads/glowforge/product-b.webp", c: "/invite-cards/leads/glowforge/product-c.webp" },
  "gorjana": { a: "/invite-cards/leads/gorjana/product-a.png", b: "/invite-cards/leads/gorjana/product-b.png", c: "/invite-cards/leads/gorjana/product-c.png" },
  "hodinkee": { a: "/invite-cards/leads/hodinkee/product-a.webp", b: "/invite-cards/leads/hodinkee/product-b.webp", c: "/invite-cards/leads/hodinkee/product-c.webp" },
  "jackery": { a: "/invite-cards/leads/jackery/product-a.png", b: "/invite-cards/leads/jackery/product-b.png", c: "/invite-cards/leads/jackery/product-c.png" },
  "jdmenginezone": { a: "/invite-cards/leads/jdmenginezone/product-a.png", b: "/invite-cards/leads/jdmenginezone/product-b.png", c: "/invite-cards/leads/jdmenginezone/product-c.png" },
  "liveu": { a: "/invite-cards/leads/liveu/product-a.png", b: "/invite-cards/leads/liveu/product-b.png", c: "/invite-cards/leads/liveu/product-c.png" },
  "mactools": { a: "/invite-cards/leads/mactools/product-a.jpg", b: "/invite-cards/leads/mactools/product-b.jpg", c: "/invite-cards/leads/mactools/product-c.jpg" },
  "magnaflow": { a: "/invite-cards/leads/magnaflow/product-a.png", b: "/invite-cards/leads/magnaflow/product-b.png", c: "/invite-cards/leads/magnaflow/product-c.png" },
  "mock-lead-invite-card": { a: "/invite-cards/leads/mock-lead-invite-card/product-a.webp", b: "/invite-cards/leads/mock-lead-invite-card/product-b.webp", c: "/invite-cards/leads/mock-lead-invite-card/product-c.webp" },
  "molekule": { a: "/invite-cards/leads/molekule/product-a.webp", b: "/invite-cards/leads/molekule/product-b.webp", c: "/invite-cards/leads/molekule/product-c.webp" },
  "nanoleaf": { a: "/invite-cards/leads/nanoleaf/product-a.jpg", b: "/invite-cards/leads/nanoleaf/product-b.jpg", c: "/invite-cards/leads/nanoleaf/product-c.png" },
  "peakdesign": { a: "/invite-cards/leads/peakdesign/product-a.webp", b: "/invite-cards/leads/peakdesign/product-b.webp", c: "/invite-cards/leads/peakdesign/product-c.webp" },
  "positivegrid": { a: "/invite-cards/leads/positivegrid/product-a.png", b: "/invite-cards/leads/positivegrid/product-b.png", c: "/invite-cards/leads/positivegrid/product-c.png" },
  "pura": { a: "/invite-cards/leads/pura/product-a.png", b: "/invite-cards/leads/pura/product-b.png", c: "/invite-cards/leads/pura/product-c.png" },
  "schoolhouse": { a: "/invite-cards/leads/schoolhouse/product-a.png", b: "/invite-cards/leads/schoolhouse/product-b.png", c: "/invite-cards/leads/schoolhouse/product-c.png" },
  "sennheiser": { a: "/invite-cards/leads/sennheiser/product-a.png", b: "/invite-cards/leads/sennheiser/product-b.png", c: "/invite-cards/leads/sennheiser/product-c.png" },
  "shapermint": { a: "/invite-cards/leads/shapermint/product-a.webp", b: "/invite-cards/leads/shapermint/product-b.webp", c: "/invite-cards/leads/shapermint/product-c.webp" },
  "sixpenny": { a: "/invite-cards/leads/sixpenny/product-a.webp", b: "/invite-cards/leads/sixpenny/product-b.webp", c: "/invite-cards/leads/sixpenny/product-c.webp" },
  "sodastream": { a: "/invite-cards/leads/sodastream/product-a.webp", b: "/invite-cards/leads/sodastream/product-b.webp", c: "/invite-cards/leads/sodastream/product-c.webp" },
  "speedengineering": { a: "/invite-cards/leads/speedengineering/product-a.png", b: "/invite-cards/leads/speedengineering/product-b.png", c: "/invite-cards/leads/speedengineering/product-c.png" },
  "thehomesecuritysuperstore": { a: "/invite-cards/leads/thehomesecuritysuperstore/product-a.png", b: "/invite-cards/leads/thehomesecuritysuperstore/product-b.png", c: "/invite-cards/leads/thehomesecuritysuperstore/product-c.png" },
  "theproscloset": { a: "/invite-cards/leads/theproscloset/product-a.jpg", b: "/invite-cards/leads/theproscloset/product-b.jpg", c: "/invite-cards/leads/theproscloset/product-c.jpg" },
  "upscale-audio": { a: "/invite-cards/leads/upscale-audio/product-a.jpg", b: "/invite-cards/leads/upscale-audio/product-b.jpg", c: "/invite-cards/leads/upscale-audio/product-c.jpg" },
  "urotuning": { a: "/invite-cards/leads/urotuning/product-a.png", b: "/invite-cards/leads/urotuning/product-b.png", c: "/invite-cards/leads/urotuning/product-c.png" },
  "uswatersystems": { a: "/invite-cards/leads/uswatersystems/product-a.png", b: "/invite-cards/leads/uswatersystems/product-b.png", c: "/invite-cards/leads/uswatersystems/product-c.png" },
};

export function resolveLeadProductPath(leadId: string, slot: LeadProductSlot): string {
  const row = LEAD_PRODUCT_URLS[leadId];
  const url = row?.[slot];
  if (url) return url;
  return `/invite-cards/leads/${leadId}/product-${slot}.jpg`;
}
