export type DemoProductCard = {
  title: string;
  price: string;
  tag: string;
};

export type LeadPilotInviteData = {
  id: string;
  storeName: string;
  storeDomain: string;
  /**
   * When non-empty after trim, the invite greeting addresses this person and
   * explains the invite is to make Bizmis available on the store.
   */
  leadContactName: string | null;
  /** Reserved for future copy; greeting uses `leadContactName` only for now. */
  leadContactLastName: string | null;
  /** Custom HTML or plain message; empty uses built-in pilot invite template */
  content: string;
  logoImagePath: string;
  /** Resolved public URL (extension chosen by sync-lead-product-manifest from disk) */
  productAImagePath: string;
  productBImagePath: string;
  productCImagePath: string;
  /** Hex, e.g. #1a2b3c */
  primaryColor: string;
  secondaryColor: string | null;
  /**
   * When set (hex), used for the highlighted store name in the card and email.
   * When null, falls back to primaryColor (e.g. set a dark hex when primary is too light for text).
   */
  textColor?: string | null;
  /**
   * When set (hex), the store header logo is recolored to this fill (CSS mask).
   * Use e.g. #ffffff when the asset matches the banner and would disappear.
   */
  logoColorOverlay?: string | null;
  /**
   * Scale factor for the store logo in the invite header (email split banner).
   * Omitted or invalid values behave as 1.0.
   */
  leadLogoScale?: number;
  /** One sentence explaining how Bizmis helps *this* store's shoppers. */
  pitchLine: string;
  /** Shopper voice prompt shown in storefront demo mockup. */
  demoShopperPrompt: string;
  /** Bizmis conversational reply in storefront demo mockup. */
  demoBizmisReply: string;
  /** Three product recommendations shown in storefront demo mockup. */
  demoProducts: [DemoProductCard, DemoProductCard, DemoProductCard];
  /** Optional explanatory footer line inside the storefront demo mockup. */
  demoFooterLine?: string;
  /** Optional short cue beside the montage avatar; falls back to `PILOT_INVITE_EMAIL_COPY.montageClerkCueDefault`. */
  montageClerkCue?: string | null;
  /** Public path to the per-lead clerk avatar render (generated by generate-early-access-avatars.py). */
  clerkAvatarImagePath: string;
  /** Unique per-store Shopify discount code for the pilot */
  couponCode: string;
  batch: number;
  wave: string;
  orderInBatch: number;
  country: string;
  vertical: string;
  subNiche: string;
};

export const PILOT_INVITE_TERMS = {
  pilotDays: 30,
  shopperCap: 500,
  storeCap: 25,
  shopifyAppUrl: "https://apps.shopify.com/bizmis",
} as const;

const HEX_OVERLAY = /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$/;

/** Resolved overlay color for masking, or null when unset / invalid. */
export function resolveLogoColorOverlay(lead: Pick<LeadPilotInviteData, "logoColorOverlay">): string | null {
  const v = lead.logoColorOverlay?.trim();
  if (!v) return null;
  return HEX_OVERLAY.test(v) ? v : null;
}

/** Effective logo scale for the invite header; defaults to 1.0 when omitted or invalid. */
export function resolveLeadLogoScale(lead: Pick<LeadPilotInviteData, "leadLogoScale">): number {
  const s = lead.leadLogoScale;
  if (typeof s !== "number" || !Number.isFinite(s) || s <= 0) return 1;
  return s;
}

/** Color for highlighted store name; invalid textColor falls back to primaryColor. */
export function resolveStoreNameTextColor(
  lead: Pick<LeadPilotInviteData, "textColor" | "primaryColor">,
): string {
  const v = lead.textColor?.trim();
  if (v && HEX_OVERLAY.test(v)) return v;
  return lead.primaryColor;
}
