/** Generated by scripts/sync-lead-product-manifest.mjs — do not edit by hand. */

export type LeadProductSlot = "a" | "b" | "c";

export const LEAD_PRODUCT_URLS: Record<string, Partial<Record<LeadProductSlot, string>>> = {
  "bluetti": { a: "/invite-cards/bluetti/product-a.webp", b: "/invite-cards/bluetti/product-b.png", c: "/invite-cards/bluetti/product-c.webp" },
  "bodega": { a: "/invite-cards/bodega/product-a.jpg", b: "/invite-cards/bodega/product-b.jpg", c: "/invite-cards/bodega/product-c.jpg" },
  "bombas": { a: "/invite-cards/bombas/product-a.png", b: "/invite-cards/bombas/product-b.png", c: "/invite-cards/bombas/product-c.png" },
  "bulova": { a: "/invite-cards/bulova/product-a.png", b: "/invite-cards/bulova/product-b.png", c: "/invite-cards/bulova/product-c.png" },
  "burrow": { a: "/invite-cards/burrow/product-a.png", b: "/invite-cards/burrow/product-b.png", c: "/invite-cards/burrow/product-c.png" },
  "crownandcaliber": { a: "/invite-cards/crownandcaliber/product-a.png", b: "/invite-cards/crownandcaliber/product-b.png", c: "/invite-cards/crownandcaliber/product-c.png" },
  "emotiva": { a: "/invite-cards/emotiva/product-a.png", b: "/invite-cards/emotiva/product-b.png", c: "/invite-cards/emotiva/product-c.png" },
  "floyd": { a: "/invite-cards/floyd/product-a.png", b: "/invite-cards/floyd/product-b.png", c: "/invite-cards/floyd/product-c.png" },
  "glossier": { a: "/invite-cards/glossier/product-a.jpg", b: "/invite-cards/glossier/product-b.jpg", c: "/invite-cards/glossier/product-c.jpg" },
  "glowforge": { a: "/invite-cards/glowforge/product-a.webp", b: "/invite-cards/glowforge/product-b.webp", c: "/invite-cards/glowforge/product-c.webp" },
  "gorjana": { a: "/invite-cards/gorjana/product-a.png", b: "/invite-cards/gorjana/product-b.png", c: "/invite-cards/gorjana/product-c.png" },
  "gymshark": { a: "/invite-cards/gymshark/product-a.jpg", b: "/invite-cards/gymshark/product-b.jpg", c: "/invite-cards/gymshark/product-c.jpg" },
  "hodinkee": { a: "/invite-cards/hodinkee/product-a.webp", b: "/invite-cards/hodinkee/product-b.webp", c: "/invite-cards/hodinkee/product-c.webp" },
  "jackery": { a: "/invite-cards/jackery/product-a.png", b: "/invite-cards/jackery/product-b.png", c: "/invite-cards/jackery/product-c.png" },
  "jdmenginezone": { a: "/invite-cards/jdmenginezone/product-a.png", b: "/invite-cards/jdmenginezone/product-b.png", c: "/invite-cards/jdmenginezone/product-c.png" },
  "liveu": { a: "/invite-cards/liveu/product-a.png", b: "/invite-cards/liveu/product-b.png", c: "/invite-cards/liveu/product-c.png" },
  "mactools": { a: "/invite-cards/mactools/product-a.jpg", b: "/invite-cards/mactools/product-b.jpg", c: "/invite-cards/mactools/product-c.jpg" },
  "magnaflow": { a: "/invite-cards/magnaflow/product-a.png", b: "/invite-cards/magnaflow/product-b.png", c: "/invite-cards/magnaflow/product-c.png" },
  "mock-lead-invite-card": { a: "/invite-cards/mock-lead-invite-card/product-a.webp", b: "/invite-cards/mock-lead-invite-card/product-b.webp", c: "/invite-cards/mock-lead-invite-card/product-c.webp" },
  "molekule": { a: "/invite-cards/molekule/product-a.webp", b: "/invite-cards/molekule/product-b.webp", c: "/invite-cards/molekule/product-c.webp" },
  "nanoleaf": { a: "/invite-cards/nanoleaf/product-a.jpg", b: "/invite-cards/nanoleaf/product-b.jpg", c: "/invite-cards/nanoleaf/product-c.png" },
  "peakdesign": { a: "/invite-cards/peakdesign/product-a.webp", b: "/invite-cards/peakdesign/product-b.webp", c: "/invite-cards/peakdesign/product-c.webp" },
  "positivegrid": { a: "/invite-cards/positivegrid/product-a.png", b: "/invite-cards/positivegrid/product-b.png", c: "/invite-cards/positivegrid/product-c.png" },
  "pura": { a: "/invite-cards/pura/product-a.png", b: "/invite-cards/pura/product-b.png", c: "/invite-cards/pura/product-c.png" },
  "ruggable": { a: "/invite-cards/ruggable/product-a.jpg", b: "/invite-cards/ruggable/product-b.jpg", c: "/invite-cards/ruggable/product-c.jpg" },
  "schoolhouse": { a: "/invite-cards/schoolhouse/product-a.png", b: "/invite-cards/schoolhouse/product-b.png", c: "/invite-cards/schoolhouse/product-c.png" },
  "sennheiser": { a: "/invite-cards/sennheiser/product-a.png", b: "/invite-cards/sennheiser/product-b.png", c: "/invite-cards/sennheiser/product-c.png" },
  "shapermint": { a: "/invite-cards/shapermint/product-a.webp", b: "/invite-cards/shapermint/product-b.webp", c: "/invite-cards/shapermint/product-c.webp" },
  "sixpenny": { a: "/invite-cards/sixpenny/product-a.webp", b: "/invite-cards/sixpenny/product-b.webp", c: "/invite-cards/sixpenny/product-c.webp" },
  "sodastream": { a: "/invite-cards/sodastream/product-a.webp", b: "/invite-cards/sodastream/product-b.webp", c: "/invite-cards/sodastream/product-c.webp" },
  "speedengineering": { a: "/invite-cards/speedengineering/product-a.png", b: "/invite-cards/speedengineering/product-b.png", c: "/invite-cards/speedengineering/product-c.png" },
  "thehomesecuritysuperstore": { a: "/invite-cards/thehomesecuritysuperstore/product-a.png", b: "/invite-cards/thehomesecuritysuperstore/product-b.png", c: "/invite-cards/thehomesecuritysuperstore/product-c.png" },
  "theproscloset": { a: "/invite-cards/theproscloset/product-a.jpg", b: "/invite-cards/theproscloset/product-b.jpg", c: "/invite-cards/theproscloset/product-c.jpg" },
  "upscale-audio": { a: "/invite-cards/upscale-audio/product-a.jpg", b: "/invite-cards/upscale-audio/product-b.jpg", c: "/invite-cards/upscale-audio/product-c.jpg" },
  "urotuning": { a: "/invite-cards/urotuning/product-a.png", b: "/invite-cards/urotuning/product-b.png", c: "/invite-cards/urotuning/product-c.png" },
  "uswatersystems": { a: "/invite-cards/uswatersystems/product-a.png", b: "/invite-cards/uswatersystems/product-b.png", c: "/invite-cards/uswatersystems/product-c.png" },
};

export function resolveLeadProductPath(leadId: string, slot: LeadProductSlot): string {
  const row = LEAD_PRODUCT_URLS[leadId];
  const url = row?.[slot];
  if (url) return url;
  return `/invite-cards/${leadId}/product-${slot}.jpg`;
}
