/** Generated by scripts/sync-lead-product-manifest.mjs — do not edit by hand. */

export type LeadProductSlot = "a" | "b" | "c";

export const LEAD_PRODUCT_URLS: Record<string, Partial<Record<LeadProductSlot, string>>> = {
  "glossier": { a: "/invite-cards/leads/glossier/product-a.jpg", b: "/invite-cards/leads/glossier/product-b.jpg", c: "/invite-cards/leads/glossier/product-c.jpg" },
  "glowforge": { a: "/invite-cards/leads/glowforge/product-a.webp", b: "/invite-cards/leads/glowforge/product-b.webp", c: "/invite-cards/leads/glowforge/product-c.webp" },
  "hodinkee": { a: "/invite-cards/leads/hodinkee/product-a.webp", b: "/invite-cards/leads/hodinkee/product-b.webp", c: "/invite-cards/leads/hodinkee/product-c.webp" },
  "molekule": { a: "/invite-cards/leads/molekule/product-a.webp", b: "/invite-cards/leads/molekule/product-b.webp", c: "/invite-cards/leads/molekule/product-c.webp" },
  "peakdesign": { a: "/invite-cards/leads/peakdesign/product-a.webp", b: "/invite-cards/leads/peakdesign/product-b.webp", c: "/invite-cards/leads/peakdesign/product-c.webp" },
  "sennheiser": { a: "/invite-cards/leads/sennheiser/product-a.png", b: "/invite-cards/leads/sennheiser/product-b.png", c: "/invite-cards/leads/sennheiser/product-c.png" },
  "shapermint": { a: "/invite-cards/leads/shapermint/product-a.webp", b: "/invite-cards/leads/shapermint/product-b.webp", c: "/invite-cards/leads/shapermint/product-c.webp" },
  "sixpenny": { a: "/invite-cards/leads/sixpenny/product-a.webp", b: "/invite-cards/leads/sixpenny/product-b.webp", c: "/invite-cards/leads/sixpenny/product-c.webp" },
  "sodastream": { a: "/invite-cards/leads/sodastream/product-a.webp", b: "/invite-cards/leads/sodastream/product-b.webp", c: "/invite-cards/leads/sodastream/product-c.webp" },
  "theproscloset": { a: "/invite-cards/leads/theproscloset/product-a.jpg", b: "/invite-cards/leads/theproscloset/product-b.jpg", c: "/invite-cards/leads/theproscloset/product-c.jpg" },
};

export function resolveLeadProductPath(leadId: string, slot: LeadProductSlot): string {
  const row = LEAD_PRODUCT_URLS[leadId];
  const url = row?.[slot];
  if (url) return url;
  return `/invite-cards/leads/${leadId}/product-${slot}.jpg`;
}
